[package]
name = "seagull"
version = "0.1.0"
authors = ["rlecomte <romain.lecomte.pub@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.0.1" 
